# Generated by Django 4.2.5 on 2023-11-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Spotik',
        ),
    ]
